var states = {
	Aguascalientes: [
		'Aguascalientes',
		'Asientos',
		'Calvillo',
		'Cosío',
		'Jesús María',
		'Pabellón de Arteaga',
		'Rincón de Romos',
		'San José de Gracia',
		'Tepezalá',
		'El Llano',
	],
	Campeche: [
		'Calkiní',
		'Campeche',
		'Carmen',
		'Champotón',
		'Hecelchakán',
		'Hopelchen',
		'Palizada',
		'Tenabo',
		'Escárcega',
		'Calakmul',
	],
	Chiapas: [
		'Chiapas',
		'Acacoyagua',
		'Acala',
		'Acapetahua',
		'Altamirano',
		'Amatán',
		'Amatenango de la Frontera',
		'Amatenango del Valle',
		'Angel Albino Corzo',
		'Arriaga',
		'Bejucal de Ocampo',
	],
	Chihuahua: [
		'Chihuahua',
		'Ahumada',
		'Aldama',
		'Allende',
		'Aquiles Serdán',
		'Ascensión',
		'Bachíniva',
		'Balleza',
		'Batopilas',
		'Bacoyna',
		'Buenaventura',
	],
	CDMX: [
		'CDMX',
		'Alvaro Obregón',
		'Azcapotzalco',
		'Benito Juárez',
		'Coyoacán',
		'Cuajimalpa',
		'Cuauhtemoc',
		'Gustavo A. Madero',
		'Iztacalco',
		'Iztapalapa',
		'Magdalena Contreras',
	],
	Hidalgo: [
		'Hidalgo',
		'Acatlán',
		'Acaxochitlán',
		'Actopan',
		'Agua Blanca de Iturbide',
		'Ajacuba',
		'Alfajayucan',
		'Almoloya',
		'Apan',
		'El Arenal',
		'Atitalaquia',
	],
	Jalisco: [
		'Jalisco',
		'Acatic',
		'Acatlán de Juárez',
		'Ahualulco de Mercado',
		'Amacueca',
		'Ameca',
		'San Juanito de Escobedo',
		'Arandas',
		'El Arenal',
		'Atemajac de Brizuela',
		'Atnego',
	],
	Nayarit: [
		'Nayarit',
		'Acaponeta',
		'Ahuacatlán',
		'Amatlán de las Cañas',
		'Compostela',
		'Huajicori',
		'Ixtlán del Río',
		'Jala',
		'Xalisco',
		'Del Nayar',
		'Rosamorada',
	],
	Puebla: [
		'Puebla',
		'Acajete',
		'Acateno',
		'Acatlán',
		'Acatzingo',
		'Acteopan',
		'Ahuacatlán',
		'Ahuatlán',
		'Ahuazontepec',
		'Ahuehuetitla',
		'Ajalpa',
	],
	Yucatán: [
		'Yucatán',
		'Abalá',
		'Acanceh',
		'Akil',
		'Baca',
		'Bokobá',
		'Buctzotz',
		'Cacalchén',
		'Calotmul',
		'Cansahcab',
		'Cantamayec',
	],
};
